# Copyright IBM Corp. 2014, 2021
# SPDX-License-Identifier: Apache-2.0

# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  paths:
    include:
    - sdk/arm/compute/

pr:
  paths:
    include:
    - sdk/arm/compute/

stages:
- template: ../../../eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
  parameters:
    ServiceDirectory: 'arm/compute'
